### ISSUE TITLE
hwloc (Hardware Locality)

### ISSUE THREAD

**Issue by bgoglin** [openhpc/submissions#10]
---
#### Software Name
hwloc (Hardware Locality)

---
#### Public URL
http://www.open-mpi.org/projects/hwloc/

---
#### Technical Overview

hwloc gathers the topology of machines and exposes it as a hierarchical tree of resources such as processor packages, cores, hardware threads, caches, NUMA nodes and even I/O devices. The hwloc library is already used/embedded in some OpenHPC components such as OpenMPI and Slurm. However, the standalone hwloc library and command-line tools would also be useful, for instance when administrator/users when to quickly display the node topology with lstopo.

---
#### Latest stable version number
1.11.5 (rc1 released last week, final next monday)

---
#### Open-source license type
BSD-3

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [x] admin

The vast majority of the code runs as non-privileged user-space. For KNL (and possibly more in the future), a systemd service can be used to gather root-only information during boot (sysfs SMBIOS files that describe the memory configuration) and make it available to normal users.

---
#### Does component require post-installation configuration.

- [x] yes
- [ ] no

If yes, please describe briefly:
Installation of a systemd service for better KNL topology detection.

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.
autotools make check runs quite a lot of tests, either for the API, or for checking that topology discovery works.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
https://www.open-mpi.org/projects/hwloc/doc/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes if anything cannot be public?!
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of hwloc as a standalone component. The starting target for inclusion is to land on the OpenHPC 1.3.1 branch.
