### ISSUE TITLE
SLEPc

### ISSUE THREAD

**Issue by takekato** [openhpc/submissions#13]
---
#### Software Name
SLEPc

---
#### Public URL
http://slepc.upv.es/

---
#### Technical Overview

SLEPc is a software library for the solution of large scale sparse eigenvalue problems on parallel computers. 

---
#### Latest stable version number
3.7.4

---
#### Open-source license type
LGPL-3.0

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [ ] yes
- [x] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by takekato** [comment]
I've made the slepc package for Open HPC as follows:
OBS: https://build.openhpc.community/package/show/home:xtcohpc:OHPCARM/slepc
specfile: https://github.com/takekato/ohpc/tree/slepc/components/parallel-libs/slepc

However I think that it needs a review to make it compliant to Open HPC spec files. 
May I ask Open HPC developers to review this packages?

**Comment by takekato** [comment]
New version of slepc has been released. 
I changed the version of this issue because  developers of slepc recommend that users use update edition of slepc.

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in https://github.com/openhpc/ohpc/issues/465 for completion of the integration work.
