### ISSUE TITLE
Scotch

### ISSUE THREAD

**Issue by takekato** [openhpc/submissions#14]
---
#### Software Name
Scotch
---
#### Public URL
http://www.labri.fr/perso/pelegrin/scotch/

---
#### Technical Overview

Scotch is a software package for graph and mesh/hypergraph partitioning and
sparse matrix ordering.

---
#### Latest stable version number
6.0.4
---
#### Open-source license type
CeCILL-C

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [ ] CMake
- [x] other

If other, please describe:
1) To build a serial processing version of scotch:

make %{?_smp_mflags}

2) To build a parallel processing version of scotch:

make %{?_smp_mflags} ptscotch

[optional]
some distributor(e.g. Open Suse) builds libscotcherr.so.0.0, libscotcherrexit.so.0.0 and libscotchmetis.so.0.0
as follows:

3) To build a serial processing version of libscotcherr.so.0.0, libscotcherrexit.so.0.0 and libscotchmetis.so.0.0:
gcc -shared -Wl,-soname=libscotcherr.so.0 -o ../lib/libscotcherr.so.0.0 libscotch/library_error.o; \
gcc -shared -Wl,-soname=libscotcherrexit.so.0 -o ../lib/libscotcherrexit.so.0.0 libscotch/library_error_exit.o; \
rm -f libscotch/library_error*.o; \
gcc -shared -Wl,-soname=libscotch.so.0 -o ../lib/libscotch.so.0.0 libscotch/*.o ../lib/libscotcherr.so.0.0 -lpthread -lgfortran -lz -lbz2 -lrt; \
gcc -shared -Wl,-soname=libscotchmetis.so.0 -o ../lib/libscotchmetis.so.0.0 libscotchmetis/*.o ../lib/libscotch.so.0.0 ../lib/libscotcherr.so.0.0

4) To build a parallel processing version of libscotcherr.so.0.0, libscotcherrexit.so.0.0 and libscotchmetis.so.0.0:

mpicc -shared -Wl,-soname=libptscotcherr.so.0 -o ../lib/libptscotcherr.so.0.0 libscotch/library_error.o; \
mpicc -shared -Wl,-soname=libptscotcherrexit.so.0 -o ../lib/libptscotcherrexit.so.0.0  libscotch/library_error_exit.o; \
rm -f libscotch/library_error*.o; \
mpicc -shared -Wl,-soname=libptscotch.so.0 -o ../lib/libptscotch.so.0.0 libscotch/*.o ../lib/libptscotcherr.so.0.0 -lgfortran -lz -lbz2 ; \
mpicc -shared -Wl,-soname=libptscotchparmetis.so.0 -o ../lib/libptscotchparmetis.so.0.0 libscotchmetis/*.o ../lib/libptscotch.so.0.0 ../lib/libptscotcherr.so.0.0

---
#### Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [ ] yes
- [x] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

A set of test programs is available in the "src/check" directory.
They can be invoked with typing  "make check" and/or "make ptcheck" in the "src/".

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
The manual is available in the "doc/scotch_user6.0.pdf" directory.

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by takekato** [comment]
I've made scotch and ptscotch(*) packages for Open HPC as follows:
(*) ptscotch is a parallel version of scotch.

[scotch ]
OBS: https://build.openhpc.community/package/show/home:xtcohpc:OHPCARM/scotch
sources and the specfile: 
https://github.com/takekato/ohpc/tree/scotch/components/serial-libs/scotch

[ptscotch]
OBS: https://build.openhpc.community/package/show/home:xtcohpc:OHPCARM/ptscotch
sources and the specfile:  https://github.com/takekato/ohpc/tree/ptscotch/components/parallel-libs/ptscotch

However I think that they need a review to make them compliant to Open HPC spec files.
May I ask Open HPC developers to review these packages?

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in https://github.com/openhpc/ohpc/issues/467 for completion of the integration work.
