### ISSUE TITLE
ParMETIS

### ISSUE THREAD

**Issue by takekato** [openhpc/submissions#15]
---
#### Software Name
ParMETIS
---
#### Public URL
http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview

---
#### Technical Overview

 ParMETIS is an MPI-based parallel library that implements a variety of algorithms for partitioning unstructured graphs, meshes, and for computing fill-reducing orderings of sparse matrices. 
 ParMETIS extends the functionality provided by METIS and includes routines that are especially suited for parallel AMR computations and large scale numerical simulations. 
 The algorithms implemented in ParMETIS are based on the parallel multilevel k-way graph-partitioning, adaptive repartitioning, and parallel multi-constrained partitioning schemes.

---
#### Latest stable version number

4.0.3
---
#### Open-source license type

custom( University of Minnesota )
---
#### Relationship to component?

- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system

- [ ] autotools-based
- [ ] CMake
- [x] other

If other, please describe:

Build with ParMetis specific Makefile as follows:
 
 make config prefix=%{_prefix} shared=1

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?

- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?

- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?

- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

 Some test programs are available in the programs/ directory.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?

- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.

The manual exists in manual/ directory(manual.pdf).

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thanks for this submission/suggestion. Unfortunately, we've looked into trying to include parmetis in the past and the custom university license prohibits redistribution. I've tried to get permission from Univ. Minnesota in the past, but didn't make progress. I'm afraid we can't include it without their permission.

**Comment by takekato** [comment]
Thank you for your comment.
I didn't know that PARMETIS has a such license problem(?)
I'll consult our colleagues with what we should do.
We would like not to mean to bother you about  license issues.

**Comment by koomie** [comment]
Unable to include due to non open-source license.
