### ISSUE TITLE
PLASMA

### ISSUE THREAD

**Issue by takekato** [openhpc/submissions#16]
---
#### Software Name
PLASMA
---
#### Public URL
https://bitbucket.org/icl/plasma

---
#### Technical Overview

Technical Overview

PLASMA is a software package for solving problems in dense linear algebra using multicore processors and Xeon Phi coprocessors. PLASMA provides implementations of state-of-the-art algorithms using cutting-edge task scheduling techniques. PLASMA currently offers a collection of routines for solving linear systems of equations, least squares problems, eigenvalue problems, and singular value problems.

---
#### Latest stable version number
2.8.0

---
#### Open-source license type
3-clause BSD

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [ ] CMake
- [x] other

If other, please describe:
PLASMA installer can be obtained from the official WEB site.
Using  it as follows, PLASMA will be built:
./setup.py --cc=gcc --fc=gfortran --blaslib="-lblas"
./configure
make

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

Those are located in testing/ directory.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?

- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?

- [x] yes
- [ ] no

If available online, please provide URL.

Manuals are located in docs/ directory.
---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by takekato** [comment]
I've made the plasma package for Open HPC as follows:
OBS:  https://build.openhpc.community/package/show/home:xtcohpc:OHPCARM/plasma

specfile: 
https://github.com/takekato/ohpc/tree/plasma/components/parallel-libs/plasma

However I think that it needs a review to make it compliant to Open HPC spec files. 

In particular, I could not determine whether this package is placed in  "components/parallel-libs" or not.
If "parallel-libs" means "the packages using MPI libraries", plasma may be put on "components/serial-libs". Because plasma does not use MPI libraries directly, although plasma performs concurrently on each cpu, 

However plasma links scalapack which use MPI libraries, so we can think that plasma uses MPI library indirectly. In this meaning, plasma should be put on  "components/parallel-libs".

At any case, plasma would be classified as "parallel-libs" from its behavior, so I put plasma on "components/parallel-libs" in the meantime.

Does anyone have a idea about this issue?

Anyway, I would like to ask Open HPC developers to review this packages.

**Comment by koomie** [comment]
> At any case, plasma would be classified as "parallel-libs" from its behavior, so I put plasma on "components/parallel-libs" in the meantime.

Agreed - parallel-libs seems like the right classification to me.

**Comment by takekato** [comment]
> > At any case, plasma would be classified as "parallel-libs" from its behavior, so I put plasma on 
> >  "components/parallel-libs" in the meantime.
> Agreed
>  - parallel-libs seems like the right classification to me.
Thank you for your response.
I'll keep this classification for the moment.

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in https://github.com/openhpc/ohpc/issues/469 for completion of the integration work.
