### ISSUE TITLE
Process Management Interface-Exascale (PMIx)

### ISSUE THREAD

**Issue by rhc54** [openhpc/submissions#17]
---
#### Software Name
Process Management Interface-Exascale (PMIx)
---
#### Public URL
https://pmix.github.io/pmix

---
#### Technical Overview

High-Performance Computing (HPC) applications have historically executed in static resource allocations using programming models that ran independently of the resident system management stack (SMS). Achieving exascale performance that is both cost-effective and fits within site-level environmental constraints will, however, require that the application and SMS collaboratively orchestrate the flow of work to optimize resource utilization and compensate for on-the-fly faults. The Process Management Interface - Exascale (PMIx) community is committed to enabling scalable workflow orchestration by defining an abstract set of interfaces by which not only applications and tools can interact with the resident SMS, but also the various SMS components can interact with each other. The PMIx software package contains the PMIx convenience library that enables SMS packages and applications to utilize the PMIx standard.

This represents new functionality, but the software package is utilized by existing OpenHPC components such as SLURM.

---
#### Latest stable version number
1.2.2

---
#### Open-source license type
3-clause BSD

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.
PMIx includes a suite of unit tests that exercise the various APIs. It also includes working examples that can be used to test against an enabled server.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.
Depends upon libevent, but that is typically included in standard distributions.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
We will be putting the man pages on the project's wiki site: https://github.com/pmix/pmix/wiki

---
#### [Optional]: Would you like to receive additional review feedback by email?
Yes, please!

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in https://github.com/openhpc/ohpc/issues/466 for completion of the integration work.
