### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by pliniosilveira** [openhpc/submissions#19]
---
#### Software Name
OpenCV - Open Source Computer Vision Library

---
#### Public URL
http://opencv.org/

---
#### Technical Overview

OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library. OpenCV was built to provide a common infrastructure for computer vision applications and to accelerate the use of machine perception in the commercial products. Being a BSD-licensed product, OpenCV makes it easy for businesses to utilize and modify the code.

The library has more than 2500 optimized algorithms, which includes a comprehensive set of both classic and state-of-the-art computer vision and machine learning algorithms. These algorithms can be used to detect and recognize faces, identify objects, classify human actions in videos, track camera movements, track moving objects, extract 3D models of objects, produce 3D point clouds from stereo cameras, stitch images together to produce a high resolution image of an entire scene, find similar images from an image database, remove red eyes from images taken using flash, follow eye movements, recognize scenery and establish markers to overlay it with augmented reality, etc. OpenCV has more than 47 thousand people of user community and estimated number of downloads exceeding 14 million. The library is used extensively in companies, research groups and by governmental bodies.

Along with well-established companies like Google, Yahoo, Microsoft, Intel, IBM, Sony, Honda, Toyota that employ the library, there are many startups such as Applied Minds, VideoSurf, and Zeitera, that make extensive use of OpenCV. OpenCV’s deployed uses span the range from stitching streetview images together, detecting intrusions in surveillance video in Israel, monitoring mine equipment in China, helping robots navigate and pick up objects at Willow Garage, detection of swimming pool drowning accidents in Europe, running interactive art in Spain and New York, checking runways for debris in Turkey, inspecting labels on products in factories around the world on to rapid face detection in Japan.

It has C++, C, Python, Java and MATLAB interfaces and supports Windows, Linux, Android and Mac OS. OpenCV leans mostly towards real-time vision applications and takes advantage of MMX and SSE instructions when available. A full-featured CUDA and OpenCL interfaces are being actively developed right now. There are over 500 algorithms and about 10 times as many functions that compose or support those algorithms. OpenCV is written natively in C++ and has a templated interface that works seamlessly with STL containers.

---
#### Latest stable version number
3.2.0

---
#### Open-source license type
3-clause BSD License
http://opencv.org/license.html

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [x] CMake
- [ ] other

Ref.: http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html
If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [ ] yes
- [x] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [x] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
I beleave openCL would be a huge helper the this library.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
http://docs.opencv.org/3.2.0/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thanks for the submission. Quick question here - I see that opencv is available in CentOS 7.3 today. I don't see it directly in SLES, but there do appear to be RPMs available that are likely useable on SLES.  Is the ask here motivated to possible include newer versions, or is it something specific to an HPC use case?

**Comment by pliniosilveira** [comment]
I didn't know it was available in CentOS. That's good.
I never tried others RPM in SLES, I used to get it from source.
In this case, I think it's OK to keep it out of OpenHPC.

**Comment by koomie** [comment]
Withdrawn. Closing this out.
