### ISSUE TITLE
MPICH

### ISSUE THREAD

**Issue by raffenet** [openhpc/submissions#2]
---
#### Software Name

MPICH

---
#### Public URL

www.mpich.org

---
#### Technical Overview

MPICH is a high performance and widely portable implementation of the Message Passing Interface (MPI) standard. Other MPI implementations in OHPC are OpenMPI and MVAPICH2.

---
#### Latest stable version number

3.2

---
#### Open-source license type

BSD

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [ ] yes
- [x] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

Tests are located in the test/mpi directory in the source, and are invoked with `make testing`. The tests exercise a large cross-section of MPI functionality to ensure compliance and correctness.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.

http://www.mpich.org/documentation/guides/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission and starting work on a companion .spec file in PR https://github.com/openhpc/ohpc/pull/270. The TSC has recommended acceptance of the MPICH library to be configured as an additional MPI family.  The starting target for inclusion is to land on the OpenHPC 1.2 branch.

**Comment by koomie** [comment]
New tracker created in https://github.com/openhpc/ohpc/issues/317 for integration work.  Closing this out.
