### ISSUE TITLE
pnetcdf

### ISSUE THREAD

**Issue by pawosm-arm** [openhpc/submissions#20]
---
#### Software Name
pnetcdf

---
#### Public URL
https://trac.mcs.anl.gov/projects/parallel-netcdf

---
#### Technical Overview

PnetCDF is a high-performance parallel I/O library for accessing files in format compatibility with
Unidata's NetCDF, specifically the formats of CDF-1, 2, and 5. The CDF-5 file format, an extension of
CDF-2, supports unsigned data types and uses 64-bit integers to allow users to define large dimensions, attributes, and variables (> 2B array elements).

This library is required by cam-se (homme) benchmark from the LLNL CORAL suite. It should be used with MPI workloads (the ones build with mpicc, mpicxx, mpif90, etc.), and for that reason it should be provided for all combinations of compiler/MPI families.

The package provides static library libpnetcdf.a. Since exported functions contain calls to MPI runtime library, all potential users should use mpi* wrappers (mpicc, mpifort, etc.) when building code depending on this library.

A pull request with ready to use specfile and imported test cases was already issued for this package and waits for acceptance.

---
#### Latest stable version number
1.8.1

---
#### Open-source license type
netCDF

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.
The release tarball contains tests directory. I managed to import the most relevant test cases to OpenHPC test suite.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
https://trac.mcs.anl.gov/projects/parallel-netcdf/wiki/Documentation

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [ ] yes
- [x] no

**Comment by pawosm-arm** [comment]
Build moved to https://build.openhpc.community/package/show/home:pawel:branches:OpenHPC:1.3:Update1:Factory/pnetcdf-gnu

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in https://github.com/openhpc/ohpc/issues/468 for completion of the integration work.
