### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by pawosm-arm** [openhpc/submissions#21]
---
#### Software Name
CMake

---
#### Public URL
https://cmake.org/

---
#### Technical Overview

CMake is an open-source, cross-platform family of tools designed to build, test and package software.
This is the newer version than provided in targeted Linux distribution. Certain packages (e.g. LLVM compilers) require more recent versions of CMake.

---
#### Latest stable version number
3.8.1

---
#### Open-source license type
BSD 3-Clause license

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [x] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.
'Tests' directory bundled in official tarballs

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
https://cmake.org/documentation

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [ ] yes
- [x] no

**Comment by pawosm-arm** [comment]
https://build.openhpc.community/package/show/home:pawel:branches:OpenHPC:1.3:Update1:Factory/cmake

**Comment by koomie** [comment]
Note that this was included as acceptance as a dependency for the build of llvm compiler toolchain which was accepted for inclusion.
