### ISSUE TITLE
mpi4py

### ISSUE THREAD

**Issue by chuckatkins** [openhpc/submissions#23]
---
#### Software Name
mpi4py

---
#### Public URL
https://bitbucket.org/mpi4py/mpi4py

---
#### Technical Overview
This package provides Python bindings for the Message Passing Interface (MPI) standard. It is implemented on top of the MPI-1/2/3 specification and exposes an API which grounds on the standard MPI-2 C++ bindings.  This is the package typically used for python and hpc to expose MPI functionality in python and compliments the MPI implementations provided by OpenHPC.

---
#### Latest stable version number
2.0.0

---
#### Open-source license type
BSD

---
#### Relationship to component?
- [ ] contributing developer
- [X] user
- [ ] other

---
#### Build system
- [ ] autotools-based
- [ ] CMake
- [X] other

If other, please describe:
python setuptools / distutils

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [X] no

If yes, please describe briefly:

Only the creation of a module file

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

Tests are included in the `tests` folder of the source package and can be run with `python setup.py test`.  They are unit tests validating that the mpi bindings are functioning as espected.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

Just python (2 or 3 is fine), which is part of standard linux distributions.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
http://pythonhosted.org/mpi4py/

---
#### [Optional]: Would you like to receive additional review feedback by email?

- [X] yes
- [ ] no

**Comment by chuckatkins** [comment]
Please see https://github.com/openhpc/ohpc/pull/534 for initial implementation

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of mpi4py. The starting target for inclusion is to land on the OpenHPC 1.3.3 branch.
