### ISSUE TITLE
slurm-spank-x11: x11 forwarding plugin for srun

### ISSUE THREAD

**Issue by adrianreber** [openhpc/submissions#28]
---
#### Software Name
slurm-spank-x11

---
#### Public URL
https://github.com/hautreux/slurm-spank-x11

---
#### Technical Overview
slurm-spank-x11 adds X11 forwarding to slurm's srun. Especially for demonstration purposes very helpful.

---
#### Latest stable version number
0.2.5

---
#### Open-source license type
GPLv3

---
#### Relationship to component?
- [ ] contributing developer
- [x] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [ ] CMake
- [x] other

If other, please describe:
Just two files to compile

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [ ] yes
- [x] no

Just a binary, a shared object and a configuration file.

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [x] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
As it is a slurm plugin it requires slurm. slurm is distributed by OpenHPC already.

---
#### Does the component include online or installable documentation?
- [ ] yes
- [x] no

If available online, please provide URL.

---
#### [Optional]: Would you like to receive additional review feedback by email?
- [x] yes
- [ ] no

**Comment by adrianreber** [comment]
See: https://github.com/openhpc/ohpc/pull/633

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of the x11 plugin. However, it was also noted the latest SLURM release is supposed to include similar functionality. From the release notes at https://github.com/SchedMD/slurm/blob/slurm-17-11-2-1/RELEASE_NOTES:

>  X11 support is now fully integrated with the main Slurm code. Remove any
    X11 plugin configured in your plugstack.conf file to avoid errors being
    logged about conflicting options.

The next OpenHPC release should pick up this latest release and the desired functionality. If not, we can revisit if a separate build is necessary.
