### ISSUE TITLE
PBS Professional

### ISSUE THREAD

**Issue by mike0042** [openhpc/submissions#3]
---
#### Software Name

PBS Professional

---
#### Public URL

http://www.pbspro.org

---
#### Technical Overview

PBS Professional® is a fast, powerful workload manager and job scheduler designed to improve productivity, optimize utilization & efficiency, and simplify administration for HPC clusters, clouds and supercomputers.

---
#### Latest stable version number

14.1

---
#### Open-source license type

GNU Affero GPL v3+

---
#### Relationship to component?
- [X] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [X] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [ ] user space
- [X] admin

---
#### Does component require post-installation configuration.

- [X] yes
- [ ] no

If yes, please describe briefly:

At a minimum, compute nodes must be added to the server using the qmgr command. There are a host of additional configuration options that impact job scheduling policy, resource access, and other operational capabilities outlined in the PBS Professional Administrator's Guide.

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

The test harness is located in the test/fw directory and the tests are located in the test/tests directory. The tests are intended to validate basic functions of PBS Pro. The test suite itself will be expanded over time to validate additional functionality and bug fixes.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.

http://www.pbsworks.com/SupportGT.aspx?d=PBS-Professional,-Documentation

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [X] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. PBS Pro is recognized as an established software used in production environments. The TSC has recommended acceptance of the open-source PBS Pro to enhance the modularity of OpenHPC by providing administrators additional flexibility on the choice of resource manager.  There are some follow-up questions which we will close with you on separately.

A new tracker has been created in https://github.com/openhpc/ohpc/issues/320 for integration work.
