### ISSUE TITLE
Paraver

### ISSUE THREAD

**Issue by jvalll3** [openhpc/submissions#31]
---
#### Software Name
Paraver

---
#### Public URL
https://tools.bsc.es/paraver

---
#### Technical Overview

Paraver was developed to respond to the need to have a qualitative global perception of the application behavior by visual inspection and then to be able to focus on the detailed quantitative analysis of the problems. Expressive power, flexibility and the capability of efficiently handling large traces are key features addressed in the design of Paraver. The clear and modular structure of Paraver plays a significant role towards achieving these targets.

---
#### Latest stable version number
4.7.1

---
#### Open-source license type
LGPL

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.
The tests are in the tests folder of the source code.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [x] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
WxWidgets -> modified LGPL
Boost -> BSL-1.0

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
https://tools.bsc.es/tools_manuals

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission and initial starting builds under OBS. The TSC has recommended acceptance of Paraver.
