### ISSUE TITLE
Dimemas

### ISSUE THREAD

**Issue by jvalll3** [openhpc/submissions#32]
---
#### Software Name
Dimemas

---
#### Public URL
https://tools.bsc.es/dimemas

---
#### Technical Overview

Dimemas is a performance analysis tool for message-passing programs. It enables the user to develop and tune parallel applications on a workstation, while providing an accurate prediction of their performance on the parallel target machine. The Dimemas simulator reconstructs the time behavior of a parallel application on a machine modeled by a set of performance parameters. Thus, performance experiments can be done easily. The supported target architecture classes include networks of workstations, single and clustered SMPs, distributed memory parallel computers, and even heterogeneous systems.

---
#### Latest stable version number
5.3.4

---
#### Open-source license type
LGPL

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [x] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [x] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
boost (BSL-1.0)
flex (BSD)
bison (LGPL)
---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
https://tools.bsc.es/tools_manuals

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission and initial starting builds under OBS. The TSC has recommended acceptance of Dimemas.

https://github.com/openhpc/ohpc/issues/704
