### ISSUE TITLE
Lack of x11 forwarding for srun in 17.11.5 packages

### ISSUE THREAD

**Issue by tuxwielder** [openhpc/submissions#35]
---
#### Software Name
slurm-ohpc-17.11.5-20.2

---
#### Public URL
https://github.com/SchedMD/slurm/blob/slurm-17-11-2-1/RELEASE_NOTES
---
#### Technical Overview
X11 forwarding for the Slurm 'srun' command doesn't work in the current OHPC slurm packages.

Issue #28 was closed with the observation that this would be the case:
https://github.com/openhpc/submissions/issues/28#issuecomment-363408420

However this feature doesn't seem to be enabled:

[csn-h0 ~]# srun --version
slurm 17.11.5
[csn-h0 ~]# srun -p cpu -N 1 --mem 16G --x11 --pty bash
srun: unrecognized option '--x11'

---
#### Latest stable version number
17.11.5-20.2

---
#### Open-source license type
GPLv3

---
#### Relationship to component?
- [ ] contributing developer
- [X] user
- [ ] other

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

**Comment by crbaird** [comment]
Hi @tuxwielder. There was a build dependency issue with slurm v17.11.5 that will be addressed in the next release, likely soon. Please follow issue https://github.com/openhpc/ohpc/issues/701.
