### ISSUE TITLE
buildtest - Software Stack Testing Framework

### ISSUE THREAD

**Issue by shahzebsiddiqui** [openhpc/submissions#36]
---
#### Software: buildtest

---
#### Documentation: http://buildtestdocs.readthedocs.io/en/latest/

---
#### Technical Overview

buildtest is a software testing framework that can automate test creation and test 
execution of one or more software stacks. buildtest can integrate with job-scheduler
(LSF, SLURM) to submit jobs to scheduler as an alternate means of testing. buildtest can
test the OpenHPC software stack collection.

---
#### Version: 0.6.1

---
#### License: GPLv3

---
#### Relationship to component?
- [X] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [X] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [ ] yes
- [X] no

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [X] yes
- [ ] no

If yes, please describe briefly:

Copy ``config.yaml``  to ``$HOME/.local/buildtest/config.yaml`` and configure this according
to site.

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [X] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.
https://buildtestdocs.readthedocs.io/en/latest/Setup.html

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [X] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of buildtest.

https://github.com/openhpc/ohpc/issues/920
