### ISSUE TITLE
BeeGFS

### ISSUE THREAD

**Issue by breuner** [openhpc/submissions#4]
---
#### Software Name

BeeGFS

---
#### Public URL

[http://www.beegfs.com](http://www.beegfs.com)

---
#### Technical Overview

BeeGFS is a parallel cluster file system, developed with a strong focus on performance and designed for very easy installation and management.  
BeeGFS transparently spreads user data across multiple servers. By increasing the number of servers and disks in the system, performance and capacity of the file system can simply be scaled to the required level, seamlessly from small clusters up to enterprise-class systems with thousands of nodes.

---
#### Latest stable version number

Version 2015.03-r18 (release date: August 16, 2016)

---
#### Open-source license type

The BeeGFS client (where the file system is mounted for user access) is a native Linux kernel module under the GPLv2.
The BeeGFS server components (where the user data is stored) are licensed under the [BeeGFS EULA](http://www.beegfs.com/docs/BeeGFS_EULA.txt)

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [x] autotools-based
- [ ] CMake
- [x] other

If other, please describe:
The included third-party packages are autotools-based. The actual BeeGFS components use our own Makefiles.

Does the current build system support staged path installations?
For example: `make install DESTIR=/tmp/foo` (or equivalent)
- [ ] yes
- [x] no

---
#### Does component run in user space or are administrative credentials required?
- [x] user space
- [x] admin

The BeeGFS client is a Linux kernel module to mount the file system, which requires admin credentials. The BeeGFS server components run in userspace can run without admin credentials, but they typically run as system services with admin credentials.

---
#### Does component require post-installation configuration.
- [x] yes
- [ ] no

If yes, please describe briefly:
The services need to be configured to connect to the same management service (hostname/IP address) and they need to know where to store that user data (a path to an existing local file system on the servers). BeeGFS comes with setup scripts for easy configuration of such basic settings.

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [x] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [x] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
(The sources the thirdparty dependencies below are included as an extra part of the BeeGFS source download and are also included into the BeeGFS built system to allow easy building of all components.)
TinyXML++ (MIT license)
Mongoose (MIT license)

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.
[BeeGFS Documentation](http://www.beegfs.com/wiki)

---
#### [Optional]: Would you like to receive additional review feedback by email?

 
- [x] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. My apologies for the delay in updating the submission.    The TSC has recommended acceptance of the BeeGFS client. We were not able to include for the 1.2 release but plan to enable for subsequent release.
