### ISSUE TITLE
OSU Micro-Benchmarks

### ISSUE THREAD

**Issue by harisubramoni** [openhpc/submissions#40]
---
#### Software Name
OSU Micro-Benchmarks

---
#### Public URL

http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.5.tar.gz

---
#### Technical Overview

Microbenchmarks suite to evaluate MPI and PGAS (OpenSHMEM, UPC, and UPC++) libraries for CPUs and GPUs.

The following MPI, OpenSHMEM, UPC and UPC++ tests are included in the OMB package:

- Point-to-Point MPI Benchmarks: Latency, multi-threaded latency, multi-pair latency, multiple bandwidth / message rate test bandwidth, bidirectional bandwidth
- Collective MPI Benchmarks: Collective latency tests for various MPI collective operations such as MPI_Allgather, MPI_Alltoall, MPI_Allreduce, MPI_Barrier, MPI_Bcast, MPI_Gather, MPI_Reduce, MPI_Reduce_Scatter, MPI_Scatter and vector collectives.
- Non-Blocking Collective (NBC) MPI Benchmarks: Collective latency and Overlap tests for various MPI collective operations such as MPI_Iallgather, MPI_Iallreduce, MPI_Ialltoall, MPI_Ibarrier, MPI_Ibcast, MPI_Igather, MPI_Ireduce, MPI_Iscatter and vector collectives.
- One-sided MPI Benchmarks: one-sided put latency, one-sided put bandwidth, one-sided put bidirectional bandwidth, one-sided get latency, one-sided get bandwidth, one-sided accumulate latency, compare and swap latency, fetch and operate and get_accumulate latency for MVAPICH2 (MPI-2 and MPI-3).
- Point-to-Point OpenSHMEM Benchmarks: put latency, get latency, message rate, atomics,
- Collective OpenSHMEM Benchmarks: collect latency, broadcast latency, reduce latency, and barrier latency
- Point-to-Point UPC Benchmarks: put latency, get latency
- Collective UPC Benchmarks: broadcast latency, scatter latency, gather latency, all_gather latency, and exchange latency
- Point-to-Point UPC++ Benchmarks: async copy put latency, async copy get latency
- Collective UPC++ Benchmarks: broadcast latency, scatter latency, gather latency, reduce latency, all_gather latency, and all_to_all latency
- Startup Benchmarks: osu_init, osu_hello

More details of the benchmarks are available in the following page

http://mvapich.cse.ohio-state.edu/benchmarks/
 
---
#### Latest stable version number
5.5

---
#### Open-source license type

The benchmarks are available under the BSD. The license is available at the following link.

http://mvapich.cse.ohio-state.edu/static/media/mvapich/LICENSE-OMB.txt

---
#### Relationship to component?
- [ X] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [ X] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X ] yes
- [ ] no

The OSU Micro-Benchmarks use the GNU build system. Therefore you can simply
use the following steps to build the MPI benchmarks.

Example:
	./configure CC=/path/to/mpicc CXX=/path/to/mpicxx
	make
	make install

---
#### Does component run in user space or are administrative credentials required?
- [ X] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [X ] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [ X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [ ] yes
- [X ] no

If yes, please briefly describe the intent and location of the tests.

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [X ] yes
- [ ] no

If yes, please list the dependencies and associated licenses.

OSU Microbenchmarks have support for transferring data from/to host to/from GPUs. If using this feature, OMB would require CUDA to be installed on the system.

---
#### Does the component include online or installable documentation?
- [X ] yes
- [ ] no

If available online, please provide URL.
http://mvapich.cse.ohio-state.edu/static/media/mvapich/README-OMB.txt

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [ X] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of the OSU micro-benchmarks as a standalone component.

https://github.com/openhpc/ohpc/issues/991
