### ISSUE TITLE
Libfabric

### ISSUE THREAD

**Issue by ChrisDowning** [openhpc/submissions#42]
---
#### Software Name
Libfabric

---
#### Public URL
https://ofiwg.github.io/libfabric/

---
#### Technical Overview

Libfabric is a framework providing interfaces to multiple underlying communication services (PSM, verbs, etc) to applications (eg OpenMPI).

---
#### Latest stable version number
1.8.1

---
#### Open-source license type
BSD or GPL v2

---
#### Relationship to component?
- [ ] contributing developer
- [X] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [ ] CMake
- [X] other

If other, please describe:
Simple configure/make.

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [ ] user space
- [X] admin
(Used purely for building applications, which are in turn user space)

---
#### Does component require post-installation configuration.

- [ ] yes
- [X] no

If yes, please describe briefly:
(Not for libfabric itself - but only useful as a precursor to other applications)

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.
Provides a set of test configurations ("fabtests" in the repository)

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.
https://ofiwg.github.io/libfabric/v1.8.1/man/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [X] yes
- [ ] no

**Comment by crbaird** [comment]
Hi @ChrisDowning - could you briefly state the benefit of packaging our own libfabric as opposed to using the distro provided one?

**Comment by ChrisDowning** [comment]
Hi @crbaird - that's a good question; basically when I originally concluded that requesting this would be a good idea, inclusion in a 1.3.x version might have been viable - in which case the OS version would be libfabric 1.7 (at the time, at least), which did not include the core component I'm interested in getting into OpenHPC - ie support for AWS EFA.

Now the OS version of libfabric in CentOS 8 is new enough, I guess that might not be an issue any more - however I think it would still be very beneficial if the OpenHPC MPI implementations were built with libfabric support enabled; using a more up-to-date libfabric than the OS one has its advantages, but is probably less important.

**Comment by ChrisDowning** [comment]
Closing this since libfabric is included in the 2.x releases.

For future reference, AWS EFA works out of the box on OpenSUSE 15.2 as the `libefa` library is pulled in as a dependency, but on CentOS 8 this library does not exist in the central package repositories and so libfabric must be recompiled after first installing the EFA driver bundle.
