### ISSUE TITLE
hpc-workspace

### ISSUE THREAD

**Issue by gerd** [openhpc/submissions#45]
---
#### Software Name

hpc-workspace

---
#### Public URL

https://github.com/holgerBerger/hpc-workspace

---
#### Technical Overview

A **workspace** is a directory created in behalf of a user, associated with a
expiration date, to prevent disks from uncontrolled filling.
The project provides user and admin tools to manage those directories.
(new functionality)

---
#### Latest stable version number

Currently **workspace** has no version number.
hash of the last commit: f621c76ea12cb3c6428819fee001394685b60958
A [tar ball](http://ftp.uni-siegen.de/hpc-workspace/hpc-workspace-f621c76.tar.gz) of the sources it provided at:
ftp://ftp.uni-siegen.de/pub/hpc-workspace/hpc-workspace-f621c76.tar.gz

---
#### Open-source license type

GPLv3

---
#### Relationship to component?
- [x] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [ ] autotools-based
- [x] CMake
- [ ] other

If other, please describe:
A spec file is located here:
http://ftp.uni-siegen.de/hpc-workspace/spec/workspace.spec

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [x] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [ ] user space
- [x] admin

---
#### Does component require post-installation configuration.

- [x] yes
- [ ] no

If yes, please describe briefly:

To provide a cronjob that runs the script `ws_expirer` is necessary.

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [x] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [x] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

It provides a test for the configuration file. (ws_validate_config)

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [x] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [x] yes
- [ ] no

If available online, please provide URL.

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [ ] yes
- [x] no

**Comment by gerd** [comment]
#### Technical Overview  (addition)

The basic idea is

- a workspace is a directory created on behalf of the user on demand
- the lifetime is limited, the directory will be deleted automatically at some point in time
- the location is determined by the administrator and can contain a random component

This approach allows the administrator a flexible allocation of resources to users. It offers a level of redirection to hide details from the user, it offers a stable user interface to the user, and it allows e.g. migration of users between different filesystems, although only over medium to large time scales, and it offers a way to get a little grip on the lifetime of data. If noone takes care of the data anymore, it will get deleted.

**Comment by adrianreber** [comment]
@gerd I like this submission. I already used workspaces over 10 years ago and it sounds like a good idea to add it to OpenHPC.

One thing I would love to see is an official release from the original github location. If the upstream author could tag a version, github would automatically provide a release tarball.

To help users configure it, it would also be really good to have a section in OpenHPC's installation guide about how to set up workspaces correctly (especially the cron jobs).

**Comment by gerd** [comment]
@adrianreber upstream as released version 1.0.0 of hpc-workspace.

A section with the title *Setting up the ws_expirer* has been added in the file 'admin-guide.md'.

**Comment by gerd** [comment]
Upstream has released version 1.1.0 of hpc-workspace.
The URL
- http://ftp.uni-siegen.de/hpc-workspace/spec/workspace.spec
points to a spec file suitable for CentOS 8.

hpc-workspace news:
- 'ws_restore -l' lists now all workspaces from all filesystems

**Comment by gerd** [comment]
Upstream has released version 1.3.0 of hpc-workspace.

The URL

- http://ftp.uni-siegen.de/hpc-workspace/spec/workspace.spec

points to a spec file suitable for CentOS 8.

Enhancements:

-  some bugfixes
-  shell completion in contribs/completion
-  correct version number 

Are there some updates of the submission process? Will hpc-workspace be accepted?

**Comment by koomie** [comment]
Sorry for the delay on this - we got sidetracked focusing on 2.x work and are revisiting open software requests now.

**Comment by koomie** [comment]
Thank you for the submission. The TSC has recommended acceptance of this component into a future release and a new tracker has been created in openhpc/ohpc#1403 for completion of the integration work.
