### ISSUE TITLE
Score-P

### ISSUE THREAD

**Issue by surak** [openhpc/submissions#7]
---
#### Software Name
Score-P

---
#### Public URL
http://www.vi-hps.org/projects/score-p/

---
#### Technical Overview
The Score-P measurement infrastructure is a highly scalable and easy-to-use tool suite for profiling, event tracing, and online analysis of HPC applications.
Score-P offers the user a maximum of convenience by supporting a number of analysis tools. Currently, it works with Periscope, Scalasca, Vampir, and Tau and is open for other tools. Score-P comes together with the new Open Trace Format Version 2, the Cube4 profiling format and the Opari2 instrumenter.

---
#### Latest stable version number
3.0

---
#### Open-source license type
BSD

---
#### Relationship to component?
- [X] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [X] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [X] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

It perform self-test on the correctness of the measurements

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.

https://silc.zih.tu-dresden.de/scorep-current/html/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [X] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds.  The TSC has recommended acceptance of Score-P to provide additional parallel profiling and analysis capabilities. The starting target for inclusion is to land on the OpenHPC 1.2 branch.

A new tracker has bee created in https://github.com/openhpc/ohpc/issues/319 for integration work. Closing this out.
