### ISSUE TITLE
Scalasca

### ISSUE THREAD

**Issue by surak** [openhpc/submissions#8]
---
#### Software Name

Scalasca

---
#### Public URL

http://www.scalasca.org

---
#### Technical Overview

The Scalasca Trace Tools are a collection of trace-based performance analysis tools that have been specifically designed for use on large-scale systems such as the IBM Blue Gene series or Cray XT and successors, but also suitable for smaller HPC platforms. While the current focus is on applications using MPI, OpenMP, POSIX threads, or hybrid MPI+OpenMP/Pthreads parallelization, support for other parallel programming paradigms may be added in the future. A distinctive feature of the Scalasca Trace Tools is its scalable automatic trace-analysis component which provides the ability to identify wait states that occur, for example, as a result of unevenly distributed workloads. Especially when trying to scale communication intensive applications to large process counts, such wait states can present severe challenges to achieving good performance. Besides merely identifying wait states, the trace analyzer is also able to pinpoint their root causes (i.e., delays), and to identify the activities on the critical path of the target application, highlighting those routines which determine the length of the program execution and therefore constitute the best candidates for optimization.

---
#### Latest stable version number

2.3.1

---
#### Open-source license type

BSD

---
#### Relationship to component?
- [X] contributing developer
- [ ] user
- [ ] other

If other, please describe:

---
#### Build system
- [X] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: ```make install DESTIR=/tmp/foo``` (or equivalent)

- [X] yes
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### Does component require post-installation configuration.

- [ ] yes
- [X] no

If yes, please describe briefly:

---
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.

Self test for correctness of the measurements

---
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [ ] yes
- [X] no

If yes, please list the dependencies and associated licenses.

---
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.

https://apps.fz-juelich.de/scalasca/releases/scalasca/2.3/docs/manual/

---
#### [Optional]: Would you like to receive additional review feedback by email?

 

- [X] yes
- [ ] no

**Comment by koomie** [comment]
Thank you for the submission and initial starting help to enable builds.  The TSC has recommended acceptance of Scalasca to provide additional parallel profiling and analysis capabilities. The starting target for inclusion is to land on the OpenHPC 1.2 branch.

A new tracker has bee created in https://github.com/openhpc/ohpc/issues/318 for integration work. Closing this out.
