### ISSUE TITLE
SIONlib

### ISSUE THREAD

**Issue by surak** [openhpc/submissions#9]
---
#### Technical Overview

SIONlib is a library for writing and reading binary data to/from several thousands of processors into one or a small number of physical files. For parallel access to files only the open and close functions are collective while writing and reading file can be done asynchronously. SIONlib provides a SIONlib file handle which substitutes the C file pointer.
#### Open-source license type

BSD-Like: This software is free but copyrighted:

Copyright (c) 2008-2016, Forschungszentrum Juelich GmbH, Federal
Republic of Germany

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
- Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
- Neither the name of the Forschungszentrum Juelich GmbH nor the names 
  of its contributors may be used to endorse or promote products derived 
  from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

---
#### Relationship to component?
- [ ] contributing developer
- [ ] user
- [X] other

If other, please describe:
#### Build system
- [X] autotools-based
- [ ] CMake
- [ ] other

If other, please describe:

Does the current build system support staged path installations?
For example: `make install DESTIR=/tmp/foo` (or equivalent)
- [X] yes, prefix
- [ ] no

---
#### Does component run in user space or are administrative credentials required?
- [X] user space
- [ ] admin

---
#### Does component require post-installation configuration.
- [X] yes
- [ ] no

If yes, please describe briefly:
The installation of SIONlib builds a number of libraries. In order to simplify the correct choice of paths and libraries the utility sionconfig outputs the correct combination of options for compiling (–cflags) or linking (–libs):

Usage: sionconfig
Print compiler and linker flags SIONlib.
  (--com|--ser|--omp|--mpi|--ompi|--gen)   select SIONlib API
  (--cflags|--libs|--path)                 select output of sionconfig
  [--32|--64]                              Precision
  [--be] [--fe] [--mic]                    Cross compile
  [--gcc]                                  for GCC Compiler
  [--c|--f77|--f90|--cxx]                  Language selection
#### If component is selected, are you willing and able to collaborate with OpenHPC maintainers during the integration process?
- [X] yes
- [ ] no

---
#### Does the component include test collateral (e.g. regression/verification tests) in the publicly shipped source?
- [X] yes
- [ ] no

If yes, please briefly describe the intent and location of the tests.
#### Does the component have additional software dependencies (beyond compilers/MPI) that are not part of standard Linux distributions?
- [X] yes
- [ ] no

If yes, please list the dependencies and associated licenses.
#### Does the component include online or installable documentation?
- [X] yes
- [ ] no

If available online, please provide URL.
#### [Optional]: Would you like to receive additional review feedback by email?

 
- [X] yes
- [ ] no

**Comment by surak** [comment]
As mentioned last week, here is the most recent version, 1.7.0 - both in standalone form and for OTF2/Scorep "tools version": http://www.fz-juelich.de/ias/jsc/EN/Expertise/Support/Software/SIONlib/sionlib-download_node.html

**Comment by adrianreber** [comment]
I am closing this as SIONlib is part of OpenHPC since 2016: https://github.com/openhpc/ohpc/blob/3.x/components/io-libs/sionlib/SPECS/sionlib.spec
